version: '3.8'

services:
  app: 
    build: .
    image: ${DOCKER_USERNAME}/alfredo_backend:latest
    platform: linux/amd64
    container_name: alfredo_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres
    container_name: alfredo_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alfredo_user
      POSTGRES_PASSWORD: alfredo_pass
      POSTGRES_DB: alfredo_mydatabase
    volumes:
      - root_pgdata:/var/lib/postgresql/data

volumes:
  root_pgdata:
